name: Enhancement
description: Enhance an existing feature
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Importance of this improvement
      options:
        - P0 - HIGHEST
        - P1 – HIGH
        - P2 – MEDIUM
        - P3 – LOW
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Request
      description: Please describe what you want to improve
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why
      description: What's wrong or could be better?
  - type: textarea
    id: links
    attributes:
      label: Links / Exemples
      description: Link, screenshot, exemple if needed.
  - type: checkboxes
    id: confirmation
    attributes:
      label: Verifications
      description: Please confirm the following checks
      options:
        - label: This improvement concerns an existing feature.
          required: true
