name: Feature
description: New Feature
title: "[Feature]: "
labels: ["Feature"]
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Importance of this feature
      options:
        - P0 - HIGHEST
        - P1 – HIGH
        - P2 – MEDIUM
        - P3 – LOW
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Request
      description: Simply describe the desired functionality.
    validations:
      required: true
  - type: textarea
    id: value
    attributes:
      label: Why
      description: What problem does it solve or what benefit does it provide?
  - type: textarea
    id: links
    attributes:
      label: Liens / exemples
      description: Links, screenshots, exemple if needed.
  - type: checkboxes
    id: confirmation
    attributes:
      label: Verifications
      description: Please confirm the following checks
      options:
        - label: This feature does not already exist in tickets or in the application
          required: true
        - label: This request is aligned with the roadmap
          required: true
