name: Task
description: This is a simple task
title: "[Task]: "
labels: ["Task"]
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Importance of this task
      options:
        - P0 - HIGHEST
        - P1 – HIGH
        - P2 – MEDIUM
        - P3 – LOW
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please provide details of your request.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your request.
      placeholder: "As [persona], I want [need] for [benefits]."
    validations:
      required: true
  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      description: Break it down into specific tasks if possible.
      value: |
        - [ ] ...
        - [ ] ...
  - type: textarea
    id: references
    attributes:
      label: References
      description: Links for specs, models, docs, discussions, tickets liés, ...
      placeholder: Refs
  - type: checkboxes
    id: confirmation
    attributes:
      label: Verifications
      description: Please confirm the following checks
      options:
        - label: This task does not already exist in tickets or in the application
          required: true
        - label: This request is aligned with the roadmap
          required: true
